
export enum SharedStatus {
    ON_REVIEW = 'ON_REVIEW',
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    PENDING = 'PENDING',
    SUSPENDED = 'SUSPENDED',
    CLOSED = 'CLOSED',
    UNDER_REVIEW = 'UNDER_REVIEW',
    TERMINATED = 'TERMINATED',
    DELETED = 'DELETED',
    ARCHIVED = 'ARCHIVED',
    BLOCKED = 'BLOCKED',
    FROZEN = 'FROZEN',
    DORMANT = 'DORMANT',
    SUSPENDED_FOR_VERIFICATION = 'SUSPENDED_FOR_VERIFICATION',
    SUSPENDED_FOR_COMPLIANCE = 'SUSPENDED_FOR_COMPLIANCE',
    SUSPENDED_FOR_SECURITY = 'SUSPENDED_FOR_SECURITY',
    SUSPENDED_FOR_FRAUD = 'SUSPENDED_FOR_FRAUD',
    SUSPENDED_FOR_ABUSE = 'SUSPENDED_FOR_ABUSE'
}
export enum AccountType {
    PERSONAL = "PERSONAL",
    SAVINGS = "SAVINGS",
    CHECKING = "CHECKING_OR_CURRENT",       // or CURRENT
    JOINT = "JOINT",
    BUSINESS = "BUSINESS",
    SALARY = "SALARY",
    FIXED_DEPOSIT = "FIXED_DEPOSIT",
    RECURRING_DEPOSIT = "RECURRING_DEPOSIT",
    NRI = "NRI",
    TRUST = "TRUST",
    STUDENT = "STUDENT",
    RETIREMENT = "RETIREMENT",
    INVESTMENT = "INVESTMENT",
    LOAN = "LOAN"
}
export enum CurrencyType {
    INR = "INR",
    USD = "USD",
    EURO = "EURO",
    JPY = "JYY"
}
export enum GenderType {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    NON_BINARY = 'NON_BINARY',
    OTHER = 'OTHER',
    UNDISCLOSED = 'UNDISCLOSED'
}

export enum MaritalStatus {
    SINGLE = 'SINGLE',
    MARRIED = 'MARRIED',
    DIVORCED = 'DIVORCED',
    WIDOWED = 'WIDOWED',
    SEPARATED = 'SEPARATED',
    PARTNERED = 'PARTNERED',
    UNDISCLOSED = 'UNDISCLOSED'
}
export enum PersonCaste {
    // Indian Castes
    GENERAL = 'GENERAL',
    OBC = 'OBC',
    SC = 'SC',
    ST = 'ST',
    EWS = 'EWS',
    // Nepali Castes
    BRAHMIN = 'BRAHMIN',
    CHHETRI = 'CHHETRI',
    NEWAR = 'NEWAR',
    TAMANG = 'TAMANG',
    MAGAR = 'MAGAR',
    RAI = 'RAI',
    LIMBU = 'LIMBU',
    SHERPA = 'SHERPA',
    THARU = 'THARU',
    DALIT = 'DALIT',
    // Common
    OTHER = 'OTHER',
    UNDISCLOSED = 'UNDISCLOSED'
}

export enum Occupation {
    UNEMPLOYED = 'UNEMPLOYED',
    STUDENT = 'STUDENT',
    SELF_EMPLOYED = 'SELF_EMPLOYED',
    EMPLOYED = 'EMPLOYED',
    RETIRED = 'RETIRED',
    BUSINESS_OWNER = 'BUSINESS_OWNER',
    FREELANCER = 'FREELANCER',
    GOVERNMENT_EMPLOYEE = 'GOVERNMENT_EMPLOYEE',
    PRIVATE_SECTOR_EMPLOYEE = 'PRIVATE_SECTOR_EMPLOYEE',
    AGRICULTURE = 'AGRICULTURE',
    HOMEMAKER = 'HOMEMAKER',
    MILITARY = 'MILITARY',
    TEACHER = 'TEACHER',
    ENGINEER = 'ENGINEER',
    DOCTOR = 'DOCTOR',
    LAWYER = 'LAWYER',
    ARTIST = 'ARTIST',
    SCIENTIST = 'SCIENTIST',
    OTHER = 'OTHER',
    UNDISCLOSED = 'UNDISCLOSED'
}
export enum EducationalQualification {
    NO_FORMAL_EDUCATION = 'NO_FORMAL_EDUCATION',
    PRIMARY_EDUCATION = 'PRIMARY_EDUCATION',
    SECONDARY_EDUCATION = 'SECONDARY_EDUCATION',
    HIGH_SCHOOL = 'HIGH_SCHOOL',
    DIPLOMA = 'DIPLOMA',
    BACHELORS = 'BACHELORS',
    MASTERS = 'MASTERS',
    DOCTORATE = 'DOCTORATE',
    POST_DOCTORATE = 'POST_DOCTORATE',
    VOCATIONAL_TRAINING = 'VOCATIONAL_TRAINING',
    PROFESSIONAL_CERTIFICATION = 'PROFESSIONAL_CERTIFICATION',
    OTHER = 'OTHER',
    UNDISCLOSED = 'UNDISCLOSED'
}

export enum PersonTitle {
    MR = 'MR',
    MRS = 'MRS',
    MISS = 'MISS',
    MS = 'MS',
    DR = 'DR',
    PROF = 'PROF',
    REV = 'REV',
    OTHER = 'OTHER',
    UNDISCLOSED = 'UNDISCLOSED'
}

export enum ChooseOptions {
    YES = 'YES',
    NO = 'NO',
    NOT_APPLICABLE = "NOT_APPLICABLE"
}

export enum DocumentType {
    PASSPORT = 'PASSPORT',
    NATIONAL_ID = 'NATIONAL_ID',
    AADHAAR = 'AADHAAR', // India
    DRIVING_LICENSE = 'DRIVING_LICENSE',
    VOTER_ID = 'VOTER_ID', // India
    SOCIAL_SECURITY_NUMBER = 'SOCIAL_SECURITY_NUMBER', // USA
    TAX_IDENTIFICATION_NUMBER = 'TAX_IDENTIFICATION_NUMBER',
    RESIDENCE_PERMIT = 'RESIDENCE_PERMIT',
    BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
    CITIZENSHIP_CERTIFICATE = 'CITIZENSHIP_CERTIFICATE',
    NRIC = 'NRIC', // Singapore
    HEALTH_CARD = 'HEALTH_CARD',
    MILITARY_ID = 'MILITARY_ID',
    STUDENT_ID = 'STUDENT_ID',
    EMPLOYEE_ID = 'EMPLOYEE_ID',
    OTHER = 'OTHER',
    UNDISCLOSED = 'UNDISCLOSED'
}

export enum IncomeRange {
    UPTO_20000 = 'UPTO_20000',
    FROM_20001_TO_50000 = 'FROM_20001_TO_50000',
    FROM_50001_TO_1_LAC = 'FROM_50001_TO_1_LAC',
    FROM_1_LAC_TO_5_LAC = 'FROM_1_LAC_TO_5_LAC',
    FROM_5_LAC_TO_10_LAC = 'FROM_5_LAC_TO_10_LAC',
    ABOVE_10_LAC = 'ABOVE_10_LAC'
}

export enum BankAccountStatusType {
    ON_REVIEW = 'ON_REVIEW',
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    PENDING = 'PENDING',
    SUSPENDED = 'SUSPENDED',
    CLOSED = 'CLOSED',
    UNDER_REVIEW = 'UNDER_REVIEW',
    TERMINATED = 'TERMINATED',
    DELETED = 'DELETED',
    ARCHIVED = 'ARCHIVED',
    BLOCKED = 'BLOCKED',
    FROZEN = 'FROZEN',
    DORMANT = 'DORMANT',
    SUSPENDED_FOR_VERIFICATION = 'SUSPENDED_FOR_VERIFICATION',
    SUSPENDED_FOR_COMPLIANCE = 'SUSPENDED_FOR_COMPLIANCE',
    SUSPENDED_FOR_SECURITY = 'SUSPENDED_FOR_SECURITY',
    SUSPENDED_FOR_FRAUD = 'SUSPENDED_FOR_FRAUD',
    SUSPENDED_FOR_ABUSE = 'SUSPENDED_FOR_ABUSE'
}

export enum AddressStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    DELETED = 'DELETED',
    NOT_SPECIFIED = 'NOT_SPECIFIED',
    SUSPENDED = 'SUSPENDED',
    ON_HOLD = 'ON_HOLD',
    BLACK_LISTED = 'BLACK_LISTED',
}
